title: Default Page
preset: page
fields:
  speech_left:
    label: Initiales ⇤
    type: text
    width: 1/2
  speech_right:
    label: Initiales ⇥
    type: text
    width: 1/2
  text:
    label: Text
    type: textarea
    size: large

